# Generated by Django 4.1.1 on 2023-03-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_colaborador', models.CharField(max_length=200, verbose_name='nombre colaborador')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('phone', models.CharField(max_length=10, verbose_name='Celular')),
                ('address', models.CharField(max_length=200, verbose_name='direccion')),
                ('date_login', models.DateField(auto_now=True, verbose_name='Ingreso')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('distractorOne', models.CharField(max_length=200, verbose_name='Distractor')),
                ('distractorTwo', models.CharField(max_length=200, verbose_name='Distractor2')),
                ('distractorThree', models.CharField(max_length=200, verbose_name='Distractor3')),
                ('answer', models.CharField(max_length=200, verbose_name='respuesta')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.secciontest')),
            ],
        ),
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datacolaboradores', verbose_name='Colaborador')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.secciontest', verbose_name='cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assigment', verbose_name='Asignacion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='Questionario')),
            ],
        ),
    ]
