# Generated by Django 4.1.7 on 2023-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='', max_length=200, verbose_name='respuesta'),
        ),
    ]
