# Generated by Django 4.1.7 on 2023-03-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answers_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='distractorOne',
        ),
        migrations.RemoveField(
            model_name='question',
            name='distractorThree',
        ),
        migrations.RemoveField(
            model_name='question',
            name='distractorTwo',
        ),
        migrations.AddField(
            model_name='question',
            name='distractor1',
            field=models.CharField(default='', max_length=200, verbose_name='Distractor1'),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor2',
            field=models.CharField(default='', max_length=200, verbose_name='Distractor2'),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor3',
            field=models.CharField(default='', max_length=200, verbose_name='Distractor3'),
        ),
    ]
