# Generated by Django 4.1.1 on 2023-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_question_distractorone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacolaboradores',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(max_length=200, verbose_name='Status'),
        ),
    ]
