# Generated by Django 4.1.7 on 2023-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_datacolaboradores_email_usuario_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="avatar",
            field=models.TextField(default="", verbose_name="Avatar"),
        ),
    ]
