# Generated by Django 4.1.7 on 2023-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_usuario_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="avatar",
        ),
        migrations.AddField(
            model_name="datacolaboradores",
            name="avatar",
            field=models.TextField(default="", verbose_name="Avatar"),
        ),
    ]
