# Generated by Django 4.1.7 on 2023-03-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_assigment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigment",
            name="score",
            field=models.FloatField(
                default=0, verbose_name="Porcentaje de calificacion"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.datacolaboradores",
            ),
        ),
    ]
