# Generated by Django 4.1.1 on 2023-03-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_assigment_score_alter_usuario_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='colaborador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.datacolaboradores', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='datacolaboradores',
            name='avatar',
            field=models.TextField(default='https://static.vecteezy.com/system/resources/previews/005/129/844/original/profile-user-icon-isolated-on-white-background-eps10-free-vector.jpg', verbose_name='Avatar'),
        ),
    ]
