# Generated by Django 4.1.7 on 2023-03-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_assigment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigment",
            name="score",
            field=models.FloatField(
                default=0, verbose_name="Porcentaje de calificacion"
            ),
        ),
    ]
