# Generated by Django 4.1.1 on 2023-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_area_alter_datacolaboradores_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='area_to_assign',
            field=models.ManyToManyField(to='api.area', verbose_name='area'),
        ),
    ]
