# Generated by Django 4.1.7 on 2023-03-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_assigment_area_to_assign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assigment",
            name="area_to_assign",
        ),
        migrations.AlterField(
            model_name="assigment",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.datacolaboradores",
                verbose_name="Colaborador",
            ),
        ),
        migrations.CreateModel(
            name="AssginmentPerSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_to_assign",
                    models.ManyToManyField(to="api.area", verbose_name="area"),
                ),
            ],
        ),
    ]
