# Generated by Django 4.1.7 on 2023-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_remove_assigment_area_to_assign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assginmentpersection",
            name="tests_to_assign",
            field=models.ManyToManyField(
                to="api.secciontest", verbose_name="cuestionario"
            ),
        ),
    ]
