# Generated by Django 4.1.7 on 2023-03-28 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_assginmentpersection_tests_to_assign"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssginmentPerSection",
            new_name="AssignmentPerSection",
        ),
    ]
